FROM docker.io/golang:1.11 as builder

RUN go get -d -v github.com/hongkailiu/test-go/cmd/ocptf
WORKDIR /go/src/github.com/hongkailiu/test-go/
RUN make CGO_ENABLED=0 GOOS=linux build-ocptf


#FROM alpine:3.6
#https://github.com/docker-library/golang/issues/97
FROM docker.io/centos:7
WORKDIR /
COPY --from=builder /go/src/github.com/hongkailiu/test-go/build/ocptf /ocptf

CMD ["/ocptf -h"]
