FROM docker.io/circleci/golang:1.13

ARG BAZELISK_VERSION=v1.0

RUN sudo apt-get install openjdk-11-jdk patch && \
        curl -OL https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-linux-amd64 && \
        sudo mv ./bazelisk-linux-amd64 /usr/bin/bazel && sudo chmod +x /usr/bin/bazel
