FROM docker.io/golang:1.11 as builder

RUN go get -d -v github.com/hongkailiu/test-go/cmd/http
WORKDIR /go/src/github.com/hongkailiu/test-go/
RUN make CGO_ENABLED=0 GOOS=linux build-http


FROM alpine:3.9
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
WORKDIR /
COPY --from=builder /go/src/github.com/hongkailiu/test-go/build/http /http
COPY pkg/http/static /static
COPY pkg/http/swagger /swagger

CMD ["/http"]
