FROM docker.io/golang:1.13 as builder

RUN go get -d -v github.com/hongkailiu/test-go/cmd/ocptf
WORKDIR /go/src/github.com/hongkailiu/test-go/
RUN make GO111MODULE=on GOPROXY="https://goproxy.io" CGO_ENABLED=0 GOOS=linux build-ocptf


#FROM alpine:3.6
#https://github.com/docker-library/golang/issues/97
FROM docker.io/fedora:29
WORKDIR /
COPY --from=builder /go/src/github.com/hongkailiu/test-go/build/ocptf /bin/ocptf

#check the required ansible version: https://github.com/openshift/openshift-ansible#setup
RUN dnf install -y unzip;\
    dnf install -y ansible-2.6.5-1.fc29;\
    dnf install -y git;\
    curl -LO https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip; \
    unzip terraform_0.11.10_linux_amd64.zip; \
    mv /terraform /bin/;\
    rm terraform_0.11.10_linux_amd64.zip

COPY test_files/ocpft/inv /inv
COPY test_files/ocpft/playbook /playbook

CMD ["/ocptf -h"]
