FROM docker.io/golang:1.12 as builder

RUN go get -d -v github.com/hongkailiu/test-go/cmd/testctl
WORKDIR /go/src/github.com/hongkailiu/test-go/
RUN make GO111MODULE=on GOPROXY="https://goproxy.io" CGO_ENABLED=0 GOOS=linux build-testctl


FROM alpine:3.10
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
WORKDIR /
COPY --from=builder /go/src/github.com/hongkailiu/test-go/build/testctl /testctl
COPY pkg/http/static /static
COPY pkg/http/swagger /swagger

CMD ["/testctl"]
