/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/hongkailiu/test-go/pkg/experimental/codegen/pkg/apis/app/v1alpha1"
	versioned2 "github.com/hongkailiu/test-go/pkg/experimental/codegen/pkg/client/clientset/versioned"
	internalinterfaces2 "github.com/hongkailiu/test-go/pkg/experimental/codegen/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha12 "github.com/hongkailiu/test-go/pkg/experimental/codegen/pkg/client/listers/app/v1alpha1"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"
)

// SVTGoInformer provides access to a shared informer and lister for
// SVTGos.
type SVTGoInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha12.SVTGoLister
}

type sVTGoInformer struct {
	factory          internalinterfaces2.SharedInformerFactory
	tweakListOptions internalinterfaces2.TweakListOptionsFunc
	namespace        string
}

// NewSVTGoInformer constructs a new informer for SVTGo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSVTGoInformer(client versioned2.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSVTGoInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSVTGoInformer constructs a new informer for SVTGo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSVTGoInformer(client versioned2.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces2.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppV1alpha1().SVTGos(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppV1alpha1().SVTGos(namespace).Watch(options)
			},
		},
		&v1alpha1.SVTGo{},
		resyncPeriod,
		indexers,
	)
}

func (f *sVTGoInformer) defaultInformer(client versioned2.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSVTGoInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sVTGoInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&v1alpha1.SVTGo{}, f.defaultInformer)
}

func (f *sVTGoInformer) Lister() v1alpha12.SVTGoLister {
	return v1alpha12.NewSVTGoLister(f.Informer().GetIndexer())
}
