swagger: "2.0"
info:
  title: Hello
  version: 0.0.1
definitions:
  error:
    type: object
    required:
    - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
paths:
  /hostname:
    get:
      operationId: getHostname
      produces:
      - text/plain
      responses:
        200:
          description: returns the hostname of the machine
          schema:
            description: the hostname of the machine
            type: string
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      produces:
        - application/json
      responses:
        '200':    # status code
          description: A JSON array of user names
          schema:
            type: array
            items:
              type: string
  /user/{userId}:
    get:
      summary: Returns a user by ID.
      parameters:
      - name: userId
        in: path
        required: true
        description: The ID of the user to return.
        type: integer
        format: int64
        minimum: 1
      produces:
      - application/json
      responses:
        '200':
          description: A user object.
          schema:
            type: object
            properties:
              id:
                type: integer
                format: int64
                example: 4
              name:
                type: string
                example: Jessica Smith
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/error"

