version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.25 # Using Go version 1.22
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Install Dependencies
          command: go get ./...

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Run tests
          command: make verify

      - run:
          name: Build binary
          command: hack/build.sh

# Define the workflow to run the job
workflows:
  version: 2
  build_workflow:
    jobs:
      - build