version: 2.1

orbs:
  yamllint: orbss/yamllint@0.0.4

jobs:
  build:
    docker:
      - image: cimg/go:1.25
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: Install Dependencies
          command: go get ./...

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Verify code
          command: make verify

      - run:
          name: Build binary
          command: hack/build.sh

  execute-yamllint:
    executor: yamllint/defaut
    steps:
      - checkout
      - yamllint/execute

# Define the workflow to run the job
workflows:
  version: 2
  build_workflow:
    jobs:
      - build

  use-my-orb:
    jobs:
      - execute-yamllint
