/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/hongkailiu/test-go/pkg/codegen/pkg/apis/app/v1alpha1"
	scheme "github.com/hongkailiu/test-go/pkg/codegen/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SVTGosGetter has a method to return a SVTGoInterface.
// A group's client should implement this interface.
type SVTGosGetter interface {
	SVTGos(namespace string) SVTGoInterface
}

// SVTGoInterface has methods to work with SVTGo resources.
type SVTGoInterface interface {
	Create(*v1alpha1.SVTGo) (*v1alpha1.SVTGo, error)
	Update(*v1alpha1.SVTGo) (*v1alpha1.SVTGo, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SVTGo, error)
	List(opts v1.ListOptions) (*v1alpha1.SVTGoList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SVTGo, err error)
	SVTGoExpansion
}

// sVTGos implements SVTGoInterface
type sVTGos struct {
	client rest.Interface
	ns     string
}

// newSVTGos returns a SVTGos
func newSVTGos(c *AppV1alpha1Client, namespace string) *sVTGos {
	return &sVTGos{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sVTGo, and returns the corresponding sVTGo object, and an error if there is any.
func (c *sVTGos) Get(name string, options v1.GetOptions) (result *v1alpha1.SVTGo, err error) {
	result = &v1alpha1.SVTGo{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("svtgos").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SVTGos that match those selectors.
func (c *sVTGos) List(opts v1.ListOptions) (result *v1alpha1.SVTGoList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SVTGoList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("svtgos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sVTGos.
func (c *sVTGos) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("svtgos").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a sVTGo and creates it.  Returns the server's representation of the sVTGo, and an error, if there is any.
func (c *sVTGos) Create(sVTGo *v1alpha1.SVTGo) (result *v1alpha1.SVTGo, err error) {
	result = &v1alpha1.SVTGo{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("svtgos").
		Body(sVTGo).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sVTGo and updates it. Returns the server's representation of the sVTGo, and an error, if there is any.
func (c *sVTGos) Update(sVTGo *v1alpha1.SVTGo) (result *v1alpha1.SVTGo, err error) {
	result = &v1alpha1.SVTGo{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("svtgos").
		Name(sVTGo.Name).
		Body(sVTGo).
		Do().
		Into(result)
	return
}

// Delete takes name of the sVTGo and deletes it. Returns an error if one occurs.
func (c *sVTGos) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("svtgos").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sVTGos) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("svtgos").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sVTGo.
func (c *sVTGos) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SVTGo, err error) {
	result = &v1alpha1.SVTGo{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("svtgos").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
