global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#prometheus-alerts'
        api_url: https://hooks.slack.com/services/{slack_api_secret}
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        text: 'aaa {{ template "slack.default.text" . }}; bbb {{ template "custom_slack_text" . }}; ccc;'

templates:
  - ./*.tmpl
