### NOT working yet: OOMKilled on openshift-online
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "test-go-build-s2i"
  namespace: hongkliu-run
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/hongkailiu/test-go"
    contextDir: .
  strategy:
    sourceStrategy:
      env:
        - name: GOCACHE
          value: /tmp/.cache
      from:
        kind: "DockerImage"
        name: "quay.io/hongkailiu/test-go:s2i-1.0.6"
  output:
    to:
      kind: "ImageStreamTag"
      name: "ci-staging:testctl-bc"
    imageLabels:
      - name: "buildBy"
        value: "openshift"
      - name: "triggerBy"
        value: "github-webhook"
