apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: cincinnati
  name: cincinnati
  namespace: cincinnati-go
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: https
    tlsConfig:
      serverName: cincinnati.cincinnati-go.svc
  scrapeClass: tls-client-certificate-auth
  selector:
    matchLabels:
      app: cincinnati
